version: '3'

services:
  puppeteer:
    image: pluswerk/puppeteer
    volumes:
    - .:/usr/src/app
    command: ["npx", "nodemon", "index.js"]
    working_dir: /usr/src/app
    ports:
    - 3000:3000
